name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug Secrets
      run: |
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}



    - name: Build and Push Docker Image
      run: |
        docker build -t yugu99/hello-world:latest .
        docker push yugu99/hello-world:latest
